### ISSUE TITLE
Helm 2 and Helm 3 release version storage names clash

### ISSUE THREAD

**Issue by gucki** [helm/helm-2to3#30] opened 2019-09-13 16:59 UTC
I just installed helm3 with 2to3 v0.1.1 and wanted to convert a simple helm2 release to helm3. However it fails:

    $ helm3 2to3 convert -t ns1 xxx
    Release "xxx" will be converted from Helm 2 to Helm 3.
    [Helm 3] Release "xxx" will be created.
    [Helm 3] ReleaseVersion "xxx.v1" will be created.
    Error: release: already exists
    Error: plugin "2to3" exited with error

I tried another release and it fails too with the same error message. In dry-run mode it doesn't complain about anything:

    $ helm3 2to3 convert --dry-run -t ns1 xxx
    NOTE: This is in dry-run mode, the following actions will not be executed.
    Run without --dry-run to take the actions described below:

    Release "xxx" will be converted from Helm 2 to Helm 3.
    [Helm 3] Release "xxx" will be created.
    [Helm 3] ReleaseVersion "xxx.v1" will be created.

There are no helm3 releases yet:

    $ helm3 ls -a
    NAME	NAMESPACE	REVISION	UPDATED	STATUS	CHART

**Comment by rimusz** [comment] 2019-09-13 17:58
can you try to run the: helm3 list -n namespace_of_your_release 
to check the helm3 releases

**Comment by gucki** [comment] 2019-09-13 18:04
The namespace I'm working on is also my current one. Adding it to the command doesn't change anything:

    $ helm3 list -a -n ns1
    NAME	NAMESPACE	REVISION	UPDATED	STATUS	CHART

There can't be any relases, it's my first usage of helm3. I know the error message sounds a bit weird... :(

**Comment by rimusz** [comment] 2019-09-13 18:24
or you try to add to convert - --tiller-out-cluster -s configmaps or secrets (depending on your setup)

**Comment by gucki** [comment] 2019-09-13 18:42
No luck:

    $ helm3 2to3 convert -t ns1 --tiller-out-cluster -s configmaps xxx
    Release "xxx" will be converted from Helm 2 to Helm 3.
    [Helm 3] Release "xxx" will be created.
    Error: xxx has no deployed releases
    Error: plugin "2to3" exited with error

    $ helm3 2to3 convert -t ns1 --tiller-out-cluster -s secrets xxx
    Release "xxx" will be converted from Helm 2 to Helm 3.
    [Helm 3] Release "xxx" will be created.
    [Helm 3] ReleaseVersion "xxx.v1" will be created.
    Error: release: already exists
    Error: plugin "2to3" exited with error

I'm using "normal" helm2, not the tiller-less one. k8s versions:

    $ kubectl version
    Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-27T17:05:32Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
    Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.5-3+8458bb6a0e2e51-dirty", GitCommit:"8458bb6a0e2e51469713683c4a8bd7c48a0c7a0c", GitTreeState:"dirty", BuildDate:"2019-07-18T10:58:36Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by rimusz** [comment] 2019-09-14 09:39
You do not really need to have tiller running in the cluster, the plugin can migrate any tiller release point I to the tiller namespace.

I cannot reproduce your error.

**Comment by rimusz** [comment] 2019-09-14 10:54
@gucki what k8s cluster you are running, on-pre/cloud/minikube?

**Comment by hickeyma** [comment] 2019-09-14 12:36
@gucki Seems like there is a secret in the cluster already with name `xxx`. Do you mind checking as follows:
`kubectl  get secrets -n ns1`

**Comment by gucki** [comment] 2019-09-15 16:34
@hickeyma You are right:

    xxx.v1                  Opaque                                1      66d
    xxx.v2                  Opaque                                1      19d

Are these from helm2? Can I safely delete them?

**Comment by gucki** [comment] 2019-09-15 16:35
@rimusz  on-prem managed with rke.

**Comment by rimusz** [comment] 2019-09-16 06:50
ok, I was able to reproduce it too, if the tiller stores releases information in the same namespace as the release itself then converting the release from v2 to v3 will fail as v2 and v3 use the same naming for secrets.
If the v2 releases are stored in the ConfigMaps than migration of the release will be successful.

**Comment by hickeyma** [comment] 2019-09-16 07:37
I have opened an issue with Helm community as the issue occurring here is because of the same naming convention for release storage in Helm 2 and Helm 3: https://github.com/helm/helm/issues/6435

**Comment by gucki** [comment] 2019-09-16 07:49
@hickeyma @rimusz Is there an easy way to convert the helm2 secrets to confimaps or does the content differ? Could the plugin do this automatically in case it detects a clash? I think this'd be the easiest solution?

**Comment by hickeyma** [comment] 2019-09-16 08:00
@gucki I don't think this is something the plugin can just workaround. It needs to migrate as Helm 3 expects the releases.

At the moment Helm 3 is in Beta so we can still work out issues before going GA.

**Comment by gucki** [comment] 2019-09-16 08:47
@hickeyma Is is because the format of the secret and configmap are different? If the plugin would state that the migration irreversible in that case, why not? Also in that case the plugin could simply delete the old releases/ secrets before creating the new ones? Otherwise I'd prefer it over a breaking change of helm3, because I assume some people already use.

**Comment by rimusz** [comment] 2019-09-16 08:49
@gucki v2 and v3 use the same secrets naming convention and as helm v3 is till in beta we need to make it right :)

**Comment by TrurlMcByte** [comment] 2019-09-21 14:19
Looks like converter do something wrong in some cases. 
I have converted all releases in all clusters, but only stable/mysql failed (in all clusters). It's really converted, but helm list can't parse it. Debug show messages like 
```
list: failed to decode release: {{ } {mysql.v3  default /api/v1/namespaces/default/secrets/mysql.v3
 ...tldr...
helm.sh/release}: parsing time "{"started_at":"0001-01-01T00:00:00Z","completed_at":"0001-01-01T00:00:00Z
","phase":""}" as ""2006-01-02T15:04:05Z07:00"": cannot parse "{"started_at":"0001-01-01T00:00:00Z","completed_at":"0001-01-01T00:00:00Z","phase":""}" as """
```
In this case repeating convert fails with ```Error: release: already exists``` error

**Comment by TrurlMcByte** [comment] 2019-09-21 14:22
inside release this part about "hooks"
```    {
      "name": "mysql-test",
      "kind": "Pod",
      "path": "mysql/templates/tests/test.yaml",
      "manifest": "apiVersion: v1\nkind: Pod\nmetadata:\n  name: mysql-test\n  namespace: default\n  labels:\n    app: mysql\n    chart: \"mysql-1.3.1\"\n    heritage: \"Tiller\"\n    release: \"mysql\"\n  annotations:\n    \"h
      "events": [
        "release_test_success"
      ],
      "last_run": {
        "started_at": "0001-01-01T00:00:00Z",
        "completed_at": "0001-01-01T00:00:00Z",
        "phase": ""
      }
    }
```

**Comment by hickeyma** [comment] 2019-09-23 08:57
@TrurlMcByte Can you raise a separate issue for this as it is different to this issue?

**Comment by rimusz** [comment] 2019-09-25 11:44
a fix is in https://github.com/helm/helm/pull/6500 which should be released in helm v3 beta 4 soon

**Comment by hickeyma** [comment] 2019-09-26 17:05
helm/helm#6435 now fixed and will be in Helm 3 Beta 4.

**Comment by hickeyma** [comment] 2019-09-26 17:05
Closing as fix now ion Helm core.

**Closed by hickeyma** 2019-09-26 17:05 UTC
Labels: bug
