### ISSUE TITLE
helm3 2to3 convert <RELEASE NAME> says invalid configuration: no configuration has been provided

### ISSUE THREAD

**Issue by sandipchitale** [helm/helm-2to3#153] opened 2020-06-18 19:01 UTC
Filing a separate issue as requested on a similar closed issue #138 

> helm3 2to3 convert --dry-run releasename
2020/06/18 11:57:00 NOTE: This is in dry-run mode, the following actions will not be executed.
2020/06/18 11:57:00 Run without --dry-run to take the actions described below:
2020/06/18 11:57:00
2020/06/18 11:57:00 Release "releasename" will be converted from Helm v2 to Helm v3.
2020/06/18 11:57:00 [Helm 3] Release "releasename" will be created.
2020/06/18 11:57:00 invalid configuration: no configuration has been provided
Error: plugin "2to3" exited with error

I am on Windows 10. I can see my release in the helm2 list. It is up and running. It is deployed to Kubernete (CFCR).

**Comment by hickeyma** [comment] 2020-06-19 18:37
@sandipchitale Thanks for raising the issue.

On the terminal that you are running the `convert` command, can you run Helm 2 commands like `helm version` and `helm ls`? It would be good to show these outputs as well.

Are you able to convert any release?

**Comment by digeler** [comment] 2020-07-01 20:09
try using elevated command prompt it helped me : 
helm3 2to3 convert enricher --dry-run
2020/07/01 23:08:46 NOTE: This is in dry-run mode, the following actions will not be executed.
2020/07/01 23:08:46 Run without --dry-run to take the actions described below:
2020/07/01 23:08:46
2020/07/01 23:08:46 Release "enricher" will be converted from Helm v2 to Helm v3.
2020/07/01 23:08:46 [Helm 3] Release "enricher" will be created.
2020/07/01 23:08:46 [Helm 3] ReleaseVersion "enricher.v1" will be created.

**Comment by hickeyma** [comment] 2020-07-07 08:28
Ping @sandipchitale. Any update?

**Comment by bobo333** [comment] 2020-07-07 20:14
I'm running into the same problem, but running on macosx. Note `helm` is `helm v2` and `helm3` is (obviously) `helm v3`

```
$ helm3   2to3 convert  --kube-context stg  prod-steve-example-laravel --dry-run
2020/07/07 13:06:58 NOTE: This is in dry-run mode, the following actions will not be executed.
2020/07/07 13:06:58 Run without --dry-run to take the actions described below:
2020/07/07 13:06:58
2020/07/07 13:06:58 Release "prod-steve-example-laravel" will be converted from Helm v2 to Helm v3.
2020/07/07 13:06:58 [Helm 3] Release "prod-steve-example-laravel" will be created.
2020/07/07 13:06:58 invalid configuration: no configuration has been provided
Error: plugin "2to3" exited with error
```

I tried explicitly passing the `kubeconfig` path thinking it may be related to the error message about invalid configuration, but got the same result

```
$ helm3   2to3 convert --kubeconfig /path/to/kubeconfig  --kube-context stg  prod-steve-example-laravel --dry-run
2020/07/07 13:07:21 NOTE: This is in dry-run mode, the following actions will not be executed.
2020/07/07 13:07:21 Run without --dry-run to take the actions described below:
2020/07/07 13:07:21
2020/07/07 13:07:21 Release "prod-steve-example-laravel" will be converted from Helm v2 to Helm v3.
2020/07/07 13:07:21 [Helm 3] Release "prod-steve-example-laravel" will be created.
2020/07/07 13:07:21 invalid configuration: no configuration has been provided
Error: plugin "2to3" exited with error
```

I can see the release exists in helm2:

```
$ helm --kube-context stg history prod-steve-example-laravel
REVISION	UPDATED                 	STATUS    	CHART                   	APP VERSION	DESCRIPTION
1       	Mon Jul  6 14:05:58 2020	SUPERSEDED	laravel-framework-1.28.0	           	719ed1a73b53
2       	Tue Jul  7 11:29:54 2020	SUPERSEDED	laravel-framework-1.28.3	           	719ed1a73b53
3       	Tue Jul  7 11:44:49 2020	DEPLOYED  	laravel-framework-1.28.0	           	719ed1a73b53
```

And I can list other releases I made with helm3:

```
$ helm3 --kube-context stg list --all-namespaces
NAME                                      	NAMESPACE                    	REVISION	UPDATED                                	STATUS  	CHART                   	APP VERSION
stg-steve-example-laravel                 	stg-steve-example-laravel    	5       	2020-07-07 18:45:12.351905774 +0000 UTC	deployed	laravel-framework-1.28.3
stg-steve-example-laravel-assets          	stg-steve-example-laravel    	5       	2020-07-07 18:22:51.31325106 +0000 UTC 	deployed	assets-upload-job-1.0.5
stg-steve-example-laravel-completed-deploy	stg-steve-example-laravel    	2       	2020-07-07 18:37:27.419605632 +0000 UTC	deployed	laravel-framework-1.28.3
stg-steve-example-laravel-ssr             	stg-steve-example-laravel-ssr	4       	2020-07-07 18:45:12.007261475 +0000 UTC	deployed	nodejs-3.12.1
```

Version info:

```
$ helm3  version
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"dirty", GoVersion:"go1.14.3"}

$ helm --kube-context stg version
Client: &version.Version{SemVer:"v2.16.9", GitCommit:"8ad7037828e5a0fca1009dabe290130da6368e39", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.7", GitCommit:"5f2584fd3d35552c4af26036f0c464191287986b", GitTreeState:"clean"}
```

**Comment by hickeyma** [comment] 2020-07-08 11:03
@bobo333 I have been unfortunately unable to reproduce this issue. I am wondering if you could add some trace and build the binary and try and identify where this is happening. At the moment, I am unsure how and where the issue is.

**Comment by bobo333** [comment] 2020-07-08 18:15
@hickeyma I figured out what the issue was - I had a (very) old version of the `2to3` plugin installed.

```
$ helm3 plugin list
NAME	VERSION	DESCRIPTION
2to3	0.2.0  	migrate and cleanup Helm v2 configuration and releases in-place to Helm v3
```

After running

```
$ helm3 plugin remove 2to3
$ helm3 plugin install https://github.com/helm/helm-2to3.git
$ helm3 plugin list
NAME	VERSION	DESCRIPTION
2to3	0.5.1  	migrate and cleanup Helm v2 configuration and releases in-place to Helm v3
```

It works!

```
$ helm3   2to3 convert --tiller-ns tiller  --kube-context stg  prod-steve-example-laravel --dry-run
2020/07/08 11:11:00 NOTE: This is in dry-run mode, the following actions will not be executed.
2020/07/08 11:11:00 Run without --dry-run to take the actions described below:
2020/07/08 11:11:00
2020/07/08 11:11:00 Release "prod-steve-example-laravel" will be converted from Helm v2 to Helm v3.
2020/07/08 11:11:00 [Helm 3] Release "prod-steve-example-laravel" will be created.
2020/07/08 11:11:01 [Helm 3] ReleaseVersion "prod-steve-example-laravel.v1" will be created.
2020/07/08 11:11:01 [Helm 3] ReleaseVersion "prod-steve-example-laravel.v2" will be created.
2020/07/08 11:11:01 [Helm 3] ReleaseVersion "prod-steve-example-laravel.v3" will be created.
```

Thanks for looking into it @hickeyma, I would assume @sandipchitale is having a similar problem and re-installing the plugin to a more recent version would fix the issue.

**Comment by hickeyma** [comment] 2020-07-09 09:18
Thanks for the feedback @bobo333. This is most helpful as I was stumped how to troubleshoot the issue.

FYI, you can update a Helm plugin without the need to remove as follows: `helm plugin update 2to3`

**Comment by hickeyma** [comment] 2020-07-09 09:20
@sandipchitale Going to close this issue following the information from @bobo333 in https://github.com/helm/helm-2to3/issues/153#issuecomment-655677220.

We can re-open if need be.

**Closed by hickeyma** 2020-07-09 09:20 UTC
Labels: question

**Comment by syednadeembe** [comment] 2020-07-16 17:31
please re-open the issue.

I'm facing the same problem with [root@vmnxkubdvm01 mosy]# helm plugin list
NAME    VERSION DESCRIPTION
2to3    0.6.0   migrate and cleanup Helm v2 configuration and releases in-place to Helm v3

**Comment by hickeyma** [comment] 2020-07-16 19:29
@syednadeembe Have a look at https://github.com/helm/helm-2to3/issues/153#issuecomment-655677220 and see if that is the issue.

**Comment by syednadeembe** [comment] 2020-07-17 04:41
@hickeyma  im on the latest version 

NAME VERSION DESCRIPTION
2to3 0.6.0 migrate and cleanup Helm v2 configuration and releases in-place to Helm v3

**Comment by hickeyma** [comment] 2020-07-17 08:37
@syednadeembe I suggest opening a new issue adding as much details in the description. Mention the OS you are running on.

Also, on the terminal that you are running the convert command, can you run Helm 2 commands like `helm version` and `helm ls?` Are you able to convert any release?

This would help to try and reproduce the issue. If you can, it might be worth building the binary with trace baked in, so might identify what is happening.  At the moment, I cannot identify where the issue is happening either.

**Comment by syednadeembe** [comment] 2020-07-18 12:56
Kool, let me do some more RCA and i will raise a new one, or perhaps a clone of this one.
