### ISSUE TITLE
Error migration : spec.clusterIP: Invalid value: "": field is immutable

### ISSUE THREAD

**Issue by sylvainmouquet** [helm/helm-2to3#125] opened 2020-02-26 13:37 UTC
Hello,

I have this error : https://github.com/helm/helm/issues/6378
In the release of helm2 there is the clusterIp is hard code and when we try to deploy with helm3 we have the error.

**Comment by hickeyma** [comment] 2020-02-26 14:38
Duplicate of #123

**Comment by hickeyma** [comment] 2020-02-26 14:38
Closing as it is a duplicate issue.

**Closed by hickeyma** 2020-02-26 14:38 UTC
