### ISSUE TITLE
convert --release-versions-max doesn't work as expected 

### ISSUE THREAD

**Issue by yannicksiewe** [helm/helm-2to3#119] opened 2020-02-17 14:49 UTC
Output of `helm version`: **v3.1.0**

Output of `kubectl version`: **v1.11.0**

Cloud Provider/Platform (AKS, GKE, Minikube etc.): **openshift 3.11**

Use case: migrate from helm 2.14 to 3.1
helm2 2to3 convert RELEASE -t xxx --release-versions-max xx (the specified maximum value is ignored, so all releases are converted)

**Comment by hickeyma** [comment] 2020-02-17 16:11
@yannicksiewe Can you provide details on what is the issue you are having?

**Comment by yannicksiewe** [comment] 2020-02-17 17:10
when use ** --release-versions-max xx** with a value for example (helm2 2to3 convert RELEASE -t xxx --release-versions-max 2 ) I must have 2 converted versions out of 5 for example, but I get 5 converted versions instead of 2

**Comment by hickeyma** [comment] 2020-02-17 17:21
I am unable to reproduce this. It might be worth first making sure that you are using the latest version of the plugin as a bug was fixed in a previous release.

Also, check the versions of a release that are stored in the cluster by Helm 2. You can use the following command to do this:
`kubectl get configmap/secret -n <tiller-namespace> -l "OWNER=TILLER"`

There might be less release version stored compared to the version number in Helm.

Then run the plugin command again to see if it is working as expected.

**Comment by yannicksiewe** [comment] 2020-02-17 17:48
plugin 2to3=v0.3.0
Already check everything 
- when run **helm2 2to3 convert xxxx -t xxxx --release-versions-max 5 --dry-run**  it printout what expected 
- This **helm2 2to3 convert xxxx -t xxxx --release-versions-max 5 ** does not give the expected result 
**exemple:**
2020/02/17 18:39:46 NOTE: The max release versions "5" is less than the actual release versions "11".
2020/02/17 18:39:46 This means only "5" of the latest release versions will be converted.
2020/02/17 18:39:46
2020/02/17 18:39:46 [Helm 3] ReleaseVersion "xxxxxx.v7" will be created.
2020/02/17 18:39:46 [Helm 3] ReleaseVersion "xxxxxx.v8" will be created.
2020/02/17 18:39:46 [Helm 3] ReleaseVersion "xxxxxx.v9" will be created.
2020/02/17 18:39:46 [Helm 3] ReleaseVersion "xxxxxx.v10" will be created.
2020/02/17 18:39:46 [Helm 3] ReleaseVersion "xxxxxx.v11" will be created.

**But I'm getting 11 converted versions**

**Comment by hickeyma** [comment] 2020-02-19 13:21
@yannicksiewe Thanks for the feedback.

Investigating it further, I still am unable to reproduce it. My testing as follows (helm2 and helm3 are aliases for the Helm versions):

```console
$ helm3 plugin list
NAME	VERSION	DESCRIPTION                                                               
2to3	0.3.0  	migrate and cleanup Helm v2 configuration and releases in-place to Helm v3

$ helm2 ls
NAME      	REVISION	UPDATED                 	STATUS  	CHART        	APP VERSION	NAMESPACE
mychart-v2	5       	Wed Feb 19 13:10:09 2020	DEPLOYED	mychart-0.1.0	1.0        	default  

$ kubectl get configmap -n kube-system -l "OWNER=TILLER"
NAME            DATA   AGE
mychart-v2.v1   1      3m24s
mychart-v2.v2   1      2m51s
mychart-v2.v3   1      49s
mychart-v2.v4   1      47s
mychart-v2.v5   1      46s

$ helm3 2to3 convert mychart-v2 --release-versions-max 2 --dry-run
2020/02/19 13:11:43 NOTE: This is in dry-run mode, the following actions will not be executed.
2020/02/19 13:11:43 Run without --dry-run to take the actions described below:
2020/02/19 13:11:43 
2020/02/19 13:11:43 Release "mychart-v2" will be converted from Helm v2 to Helm v3.
2020/02/19 13:11:43 [Helm 3] Release "mychart-v2" will be created.
2020/02/19 13:11:43 
2020/02/19 13:11:43 NOTE: The max release versions "2" is less than the actual release versions "5".
2020/02/19 13:11:43 This means only "2" of the latest release versions will be converted.
2020/02/19 13:11:43 
2020/02/19 13:11:43 [Helm 3] ReleaseVersion "mychart-v2.v4" will be created.
2020/02/19 13:11:43 [Helm 3] ReleaseVersion "mychart-v2.v5" will be created.

$ helm3 2to3 convert mychart-v2 --release-versions-max 2
2020/02/19 13:11:52 Release "mychart-v2" will be converted from Helm v2 to Helm v3.
2020/02/19 13:11:52 [Helm 3] Release "mychart-v2" will be created.
2020/02/19 13:11:53 
2020/02/19 13:11:53 NOTE: The max release versions "2" is less than the actual release versions "5".
2020/02/19 13:11:53 This means only "2" of the latest release versions will be converted.
2020/02/19 13:11:53 
2020/02/19 13:11:53 [Helm 3] ReleaseVersion "mychart-v2.v4" will be created.
2020/02/19 13:11:53 [Helm 3] ReleaseVersion "mychart-v2.v4" created.
2020/02/19 13:11:53 [Helm 3] ReleaseVersion "mychart-v2.v5" will be created.
2020/02/19 13:11:53 [Helm 3] ReleaseVersion "mychart-v2.v5" created.
2020/02/19 13:11:53 [Helm 3] Release "mychart-v2" created.
2020/02/19 13:11:53 Release "mychart-v2" was converted successfully from Helm v2 to Helm v3.
2020/02/19 13:11:53 Note: The v2 release information still remains and should be removed to avoid conflicts with the migrated v3 release.
2020/02/19 13:11:53 v2 release information should only be removed using `helm 2to3` cleanup and when all releases have been migrated over.

$ helm3 ls
NAME      	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART          	APP VERSION
mychart-v2	default  	5       	2020-02-19 13:10:09.653615902 +0000 UTC	deployed	mychart-0.1.0  	1.0

$ kubectl get secret --all-namespaces -l "owner=helm"
NAMESPACE   NAME                               TYPE                 DATA   AGE
default     sh.helm.release.v1.mychart-v2.v4   helm.sh/release.v1   1      42s
default     sh.helm.release.v1.mychart-v2.v5   helm.sh/release.v1   1      42s
```

If you could troubleshoot your set-up some more, you might be able to provide more details that would help shed more light on the issue.

**Comment by hickeyma** [comment] 2020-02-19 13:22
> But I'm getting 11 converted versions

BTW, how are you testing that you have 11 versions?

**Comment by yannicksiewe** [comment] 2020-02-24 00:26
With **kubectl get secret -n xxxxx**

**Comment by hickeyma** [comment] 2020-02-25 12:30
@yannicksiewe Can you run the following command and show we the output: `kubectl get secret -n <namespace> -l "owner=helm"`?

I am trying to better troubleshoot your issue but have been unable to reproduce it so far.

**Comment by hickeyma** [comment] 2020-03-02 10:33
@yannicksiewe Do you have any update on this issue?

**Comment by hickeyma** [comment] 2020-03-06 11:17
@yannicksiewe I am going to close this issue as I have been unable to reproduce it. If you find how to reproduce this then we can re-open the issue.

**Closed by hickeyma** 2020-03-06 11:17 UTC
Labels: question
